version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: helloworld
    ports:
      - "80:3000"

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld