version: "3"
services:
  app:
    restart: on-failure
    env_file:
      - .env.production.local
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld